### ISSUE TITLE
Mispelling of services in .travis.yml

### ISSUE THREAD

**Issue by rpeach-sag** [CallumAttryde/apama_file_plugin#3]
https://github.com/CallumAttryde/apama_file_transport/blob/200d00ab47940cc855ff03b19c6a06b68c843776/.travis.yml#L1

**Comment by CallumAttryde** [comment]
Fixed at https://github.com/CallumAttryde/apama_file_plugin/commit/9e5daf7045232edd97de7485b282ba3e307f081d
